#.travis.yml
sudo: required
notifications:
  slack: iip-foundations:qelvG0h8gO80cYsBV2vu7TPU
# blacklist
branches:
  except:
    - 8.0
    - 9.0
    - develop
## whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
- docker pull postgres
- docker pull odoo

script:
- "docker version && docker info"
- docker-compose build
- ./build/build-docker-dev.sh
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push dddigitalglobe/dockercompose_odoo
