#.travis.yml
sudo: required

# blacklist
branches:
  except:
    - 8.0
    - 9.0
    - develop
# whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
- docker pull postgres
- docker pull odoo

script:
- ./run "docker version && docker info"
- ./run docker-compose build 
- ./run docker-compose up
