#.travis.yml
sudo: required

# blacklist
branches:
  except:
    - 8.0
    - 9.0
    - develop
# whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
- docker pull postgres
- docker pull odoo

script:
- "docker version && docker info"
- docker-compose build 
- docker-compose up
- docker push dddigitalkglobe/dockercompose_odoo_1
