#.travis.yml
sudo: required

# blacklist
branches:
  except:
    - 8.0
    - 9.0
    - develop
# whitelist
branches:
  only:
    - master

services:
  - docker

before_install:
- docker pull postgres
- docker pull odoo

script:
- "docker version && docker info"
- docker-compose stop
- docker-compose rm
- docker-compose build -t dddigitalglobe/dockercompose_odoo_1 
- docker-compose up -d
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push dddigitalglobe/dockercompose_odoo_1
