db:
  image: postgres:latest
  container_name: dd_db
  environment:
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
  stdin_open: true
  tty: true
  
odoo:
  image: odoo:latest
  container_name: dd_odoo
  links:
    - db:db
  ports:
    - "127.0.0.1:80:8069" 
  stdin_open: true
  tty: true
