db:
  image: postgres:latest
  environment:
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
  volumes:
    - data:/var/lib/postgresql/data/
    restart: always
  stdin_open: true
  tty: true
  
odoo:
  image: odoo:8.0
  links:
    - db:db
  ports:
    - "127.0.0.1:80:8069" 
  volumes:
    - extra-addons:/mnt/extra-addons
    restart: always
  stdin_open: true
  tty: true
